### ISSUE TITLE
Example buying an item from ebay?

### ISSUE THREAD

**Issue by hems** [hendt/ebay-api#1]
Hello, thanks a lot for sharing this library, I really appreciate your work!

I'm trying to figure out a way to:

 1. Find and item I'm looking for ( for instance Madonna - Like a Virgin )
 2. Select the itemId from the search query
 3. Buy the item using my ebay and paypal account

This way I could "Automatically buy" an item that meets my requirements.

I tried to understand how this works from the eBay Documentation but I didn't manage to find a way yet, hopefully it's going to be much easier using your library.

Again, thank you very much.

**Comment by dantio** [comment]
Hey,
thank you!

> 1. Find and item I'm looking for ( for instance Madonna - Like a Virgin )
Check out: https://hendt.github.io/ebay-api/. I added a search field. You need an App ID and Cert ID (create a eBay Developer Account). 

> 2. Select the `itemId` from the search query
From the JSON result you can pick the `itemId`.

> 3. Buy the item using my ebay and paypal account
Ok this get's probably tricky. I never used the Order API before.

You probably need to check out:
1. https://developer.ebay.com/api-docs/buy/order/resources/checkout_session/methods/initiateCheckoutSession
2. https://developer.ebay.com/api-docs/buy/order/resources/checkout_session/methods/placeOrder

Let me know how it worked for you!
