### ISSUE TITLE
No documentation for refreshing tokens

### ISSUE THREAD

**Issue by olliechick** [hendt/ebay-api#10]
From looking at the code, it appears to automatically refresh the token if a request is made with an expired token. However, I want to sometimes refresh the token myself (and store the token in a database), to avoid extra (wasted) API calls with an expired token. 

I see there are `refreshToken`, `refreshClientToken`, and `refreshAuthToken` methods exposed in `oAuth2`, but no documentation on how to use them. I want to know how to retrieve the refreshed token that `refreshAuthToken` is presumably getting from eBay.

**Comment by dantio** [comment]
That is correct. It get's refreshed automatically. Are you sure eBay is counting the refresh token API calls?
I'll think about how to make it configurable.

You can refresh the token with:
const token = await ebay.auth.oAuth2. refreshToken();

**Comment by olliechick** [comment]
Thanks for your reply!

I'm more concerned about the overhead of making extra API calls than eBay's limit, but I assume they do count the refresh token API calls against the daily limit as well.

From the signatures, it looks like `refreshToken` returns (a Promise containing) `void` if it refreshes an auth token (instead of a client token). It will be fairly trivial for me to check if the token needs refreshing, from looking at when it expires, but it would be great to be able to store the refreshed token to avoid having to refresh it each time.

**Comment by dantio** [comment]
You are right, eBay has limitation: https://developer.ebay.com/api-docs/static/oauth-rate-limits.html
But it's 50,000 requests/day for refresh token. 

> refreshToken returns (a Promise containing) void

Good catch. It should return the token.

However, you can get the token with: `eBay.auth.oAuth2.getCredentials()` after calling `await refreshToken()`.

**Comment by olliechick** [comment]
Ok, that is a good workaround. I'll try and get `refreshAuthToken` to return its token and submit a merge request.
