### ISSUE TITLE
findItemsAdvanced: error to search products by keywords

### ISSUE THREAD

**Issue by juanremi** [hendt/ebay-api#100]
Hi, when i try to get some products using a little code variation of your example, i got the error: 
`EbayApiError: Keyword or category ID are required.`

The next is my code

```
eBay.finding.findItemsAdvanced({
    keywords: 'katze'
}).then(result => {
    console.log(result);
});
```

based in the example:
Finding - findItemsAdvanced (findItemsByKeywords)

**Comment by dantio** [comment]
Thank you for reportig this bug. Should be fixed now. Try with `v5.1.1`.

**Comment by shopeandodev** [comment]
thanks, now works

**Comment by juanremi** [comment]
Thanks, now is working :)
