### ISSUE TITLE
Where is the Merchandising API in this library?  Can't seem to find it.

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#103]
I'm probably mistaken but I've been searching your library for the `getMostWatchedItems`, `getRelatedCategoryItems`, `getSimilarItems`, and `getVersion` calls but can't seem to find them anywhere.  It's the calls listed here: [https://developer.ebay.com/Devzone/merchandising/docs/CallRef/index.html](https://developer.ebay.com/Devzone/merchandising/docs/CallRef/index.html).  Kindly, please let me know how I can use hendt / ebay-api for making these calls.  Thank you.

**Comment by dantio** [comment]
You are right. This API is not implemented yet.

**Comment by dantio** [comment]
@doverradio I have added the missed merchendising API. Please try it out :)

**Comment by dantio** [comment]
@doverradio Have you had time to test it? Can I close this ticket?
