### ISSUE TITLE
Feed API 's uploadFile not working

### ISSUE THREAD

**Issue by fr3shn3ss** [hendt/ebay-api#104]
I keep getting this error when trying to upload a file 

`      "errorId": 2005,
      "domain": "ACCESS",
      "category": "REQUEST",
      "message": "Unsupported or not specified media type",
      "longMessage": "Media type in the request is either missing or unsupported."`

**Code to upload the file using form-data. I first  create the task then use that ID to upload the file. I've tried xml,csv and xml-zipped**

var form1 = new URLSearchParams();
form1.append("file", fs.createReadStream("test.xml"));
form1.append('fileName', 'test.xml');
form1.append("name", "file");
form1.append("type", "form-data");
// form1.append('contentType', 'text/html');
main();
async function main() {
  try {  
    // const item = await eBay.sell.feed.createTask({
      //   schemaVersion: "583",
      //   feedType: "LMS_ADD_FIXED_PRICE_ITEM",
      // });
      //////////////////// 
      // const item = await eBay.sell.feed.getTasks({ feedType : "LMS_ADD_FIXED_PRICE_ITEM"})
      const item = await eBay.sell.feed.uploadFile('task-1-124013',form1)
      console.log(JSON.stringify(item, null, 2));
  } catch (e) {
    console.log(e) 
    }
}

**Comment by dantio** [comment]
Is it nodejs or browser environment?
I would suggest to try with `FormData` instead of  `URLSearchParams`.
Something like this for nodejs
```
import FormData from 'form-data'; // https://www.npmjs.com/package/form-data
const form1 = new FormData();

form1.append("file", fs.createReadStream("test.xml"));
form1.append('fileName', 'test.xml');
form1.append("name", "file");
form1.append("type", "form-data");

const item = await eBay.sell.feed.api({
  headers: form1.getHeaders()
}).uploadFile('task-1-124013',form1)

````

**Comment by fr3shn3ss** [comment]
Oh darnnnnnnnn it worked! You can't believe how hard I tried to do this. Please send me your paypal email so that I can buy you a virtual coffee :)

**Comment by dantio** [comment]
No prob, a Star would be enough :)
