### ISSUE TITLE
Error: write EPROTO 

### ISSUE THREAD

**Issue by laxman-ram-iconnect** [hendt/ebay-api#112]
Hi Team

eBay getOrder API failing and giving below error, this started happening from 30th March, before that all was working good. still facing this issue.

###error log
{ Error: write EPROTO 140637827845120:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 70 at WriteWrap.afterWrite (net.js:788:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }

**Comment by dantio** [comment]
Hey, are you using it with Node or in a Browser environment?

**Comment by dantio** [comment]
Maybe you have some outdated ssl certs. Try to update your system like apt update && apt upgrade

**Comment by laxman-ram-iconnect** [comment]
@dantio I am using it with node

**Comment by dantio** [comment]
@laxman-ram-iconnect any update on this? Was it possible to fix it with updated certs?

**Comment by laxman-ram-iconnect** [comment]
@dantio I was able to fix it after upgrading to the latest version ^7.0.0. I was using the version ^1.13.1
