### ISSUE TITLE
rlogID?  Ebay is asking me for this

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#113]
Hello,

The app I created which uses some functionality from your library is now rejecting every listing I attempt, saying it's missing business policies or the policies are invalid.  

Accordingly, I opened a developer support ticket and now they asked me for the CAL log and rlogID:
```
Can you please provide the CAL log of the failed call ?  You will find rlogID in the response header.  It will help to us to triage your issue. 
```

Is this something I can obtain from when I try to use, say, `AddFixedPriceItem` calls?  If so, how?

How would you respond to the developer support question about `CAL log` and `rlogID`?

**Comment by dantio** [comment]
Check Out the param 'returnResponse'. Set it to true and you should der the whole Response.

**Comment by doverradio** [comment]
Thank you for that.

I found the example for `returnResponse` on the readme.

However, when I tried to run it, it doesn't seem to return those values but I suspect I am calling this wrongly...
```
result = await eBay.trading.AddItem( a.post ).api({
              returnResponse: true, // return the response instead of data
            })
            .catch( ebayError => { 
              console.log( `Catching the ebayError... `, ebayError )
              a.ebayError = `${ ebayError }`
            } )
```

Is this the way I would apply `returnResponse` in the context of `AddItem`?

**Comment by doverradio** [comment]
Ok, I followed your advice and constructed this following code:
```
let result = await eBay.trading.AddItem( a.post, {
              returnResponse: true
            } )
console.log( result )
```

The result:
```
undefined
```

Got another way to try it?  Perhaps I'm making the call wrong?

**Comment by dantio** [comment]
Hm it should work. https://github.com/hendt/ebay-api/blob/master/src/api/traditional/XMLRequest.ts#L189
Do you have the latest version ? (I removed the @hendt namespace, it's only "ebay-api" now)
`npm i ebay-api@latest`

**Comment by doverradio** [comment]
Worked perfectly!  Thank you!  Closing this.
