### ISSUE TITLE
What is the best way to bulk list items to ebay?

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#115]
I have thousands of items and multiple eBay accounts.  

They are mostly variation items with differing prices per color and size variation.

What's the best way to bulk list all the items?

Previously, I had everything listed one at a time, using either the addItem or addVariationItem calls.

But that can't be how large sellers manage things if in my situation.

What is the preferred way, the eBay API of choice, that best accomplishes this task?

Likewise, for updating the price and stock for all SKUs multiple times per day?

Is there a one-shot call or upload way which can do this?

**Comment by dantio** [comment]
@doverradio you should ask this question on a eBay forum or stackoverflow I can't help you here. After a quick search, maybe https://developer.ebay.com/api-docs/sell/inventory/resources/inventory_item/methods/bulkUpdatePriceQuantity is something what you are looking for?

**Comment by doverradio** [comment]
In the end, I just use AddFixedPriceItem/ReviseFixedPriceItem for most of these calls, even if they run into the thousands.  It works for my use case.  I saw there is the Inventory API to do bulk listing but they require you to have warehouses and, unfortunately, I don't yet have a warehouse.
