### ISSUE TITLE
Additional headers not sent in traditional APIs

### ISSUE THREAD

**Issue by dege88** [hendt/ebay-api#116]
* [x] Are you running the latest version? Yes, version 7.0.0
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?

**Describe the bug**
The additional headers for the traditional APIs are not sent. This is an issue when using the traditional APIs and trying to send the `X-EBAY-SOA-GLOBAL-ID` header to change the ebay site.

### Code
```js
const eBay = new eBayApi({
  appId: '<redacted>',
  certId: '<redacted>',
  siteId: 101,
  marketplaceId: 'EBAY_IT',
  acceptLanguage: 'it_IT',
  contentLanguage: 'it-IT',
  sandbox: false,
});
let apiResult = await eBay.finding.findItemsByKeywords({
    keywords: ['marvel'],
    paginationInput: {
    entriesPerPage: 2,
  },
  outputSelector: ['AspectHistogram'],
  headers: {
    'X-EBAY-SOA-GLOBAL-ID': 'EBAY-IT', // this header is not sent in the request!
  },
});
```

### Output
The results has ebay.com entries

### expected data
There should only be ebay.it results

A way to bypass the problem is to add this into the configuration object of eBayApi:
```js
axiosConfig: {
  headers: {
    'X-EBAY-SOA-GLOBAL-ID': 'EBAY-IT',
  },
},
```
But I would prefer to have a real solution instead of an hack.

**Comment by dantio** [comment]
Headers must be defined in the second paramter:
```js
let apiResult = await eBay.finding.findItemsByKeywords(
{
    keywords: ['marvel'],
    paginationInput: {
    entriesPerPage: 2,
  },
  outputSelector: ['AspectHistogram'],
}, {
headers: {
    'X-EBAY-SOA-GLOBAL-ID': 'EBAY-IT', // this header is not sent in the request!
});```

**Comment by dege88** [comment]
You're right, I've misread the documentation, thank you for the help!
