### ISSUE TITLE
Item compatibility values returned by GetItem call are wrongly casted into non-string types

### ISSUE THREAD

**Issue by alvin-partly** [hendt/ebay-api#125]
Hello,

I've a piece of code that calls `GetItem` (Trading API) with `IncludeItemCompatibilityList` sets to true:

```js
const response = await ebayApi.trading.GetItem({
    ItemID: externalItemId,
    IncludeItemCompatibilityList: true
});
```

In the `response`, some values in the item compatibility list were undesirably casted into non-string types. This is an example item compatibility from an actual response:

```js
$ console.log(JSON.stringify(response.Item.ItemCompatibilityList))
{
	"Compatibility": [{
		"NameValueList": ["", {
			"Name": "Car Make",
			"Value": "Skoda"
		}, {
			"Name": "Model",
			"Value": "Fabia"
		}, {
			"Name": "Cars Year",
			"Value": 2019
		}, {
			"Name": "Variant",
			"Value": "Petrol Hatch"
		}, {
			"Name": "BodyStyle",
			"Value": "FWD III NJ3"
		}, {
			"Name": "Cars Type",
			"Value": 1
		}, {
			"Name": "Engine",
			"Value": "999cc 44KW 60HP CHYA;CHYE"
		}],
		"CompatibilityNotes": ""
	}]
}
```

As can be seen, the value of Cars Type had been parsed into the integer value `1`, instead of the string value `"1.0"` returned by the eBay API in the XML response. This is incorrect because `"1.0"` is the name of a car type instead of being a numerical value. This prevents us to do string matching based on the item compatibility values, because the numeric `1` will be stringified into `"1"` instead of `"1.0"`.

Would it be possible to always parse item compatibility values into the string type? 

Please note that this problem might possibly affect `getOffers` (Inventory API) too, because item compatibilities are also included in its returned value. 

I'm running version 5.3.1.

Thank you.

**Comment by dantio** [comment]
Under the hood the XML is parsed by fast-xml-parser.
```js
const response = await ebayApi.trading.GetItem({
    ItemID: externalItemId,
    IncludeItemCompatibilityList: true
}, {
  parseOptions: {
    parseNodeValue: false, // set it to false to disable the whole value parsing or
    numParseOptions: { // this is available now in v7.1.2
      skipLike: /\d+\.\d+/ // not tested
    }
  }
});
```
Check the whole Doc here: https://github.com/NaturalIntelligence/fast-xml-parser/blob/HEAD/docs/v3/docs.md
