### ISSUE TITLE
What is EBAY_RU_NAME and DEBUGX=ebay:*;?

### ISSUE THREAD

**Issue by tariqazmat101** [hendt/ebay-api#126]
Hi apoligies for asking, I've tried to dig around the codebase and perhaps get a hint at what these environment variables mean but I have no clue.

**Comment by kapooky** [comment]
Found some information about it: 
https://forums.developer.ebay.com/questions/41756/were-do-i-find-the-ru-name-or-runame.html

**Comment by tariqazmat101** [comment]
I'm sorry f

**Comment by dantio** [comment]
Ru_name is "return url" it's the url ebay will redirect the user after successful login. 
This url you have to set in your ebay developer Account. It's the url where your app is hosted and get's the code parameter from the url. I hope it helps.
