### ISSUE TITLE
GetToken failing with statuscode:400

### ISSUE THREAD

**Issue by kapooky** [hendt/ebay-api#127]
Hello I am trying to get the GetToken API to work to enable automatic refreshing of tokens (GetTokens will return an object that has a Refresh token in it's field). 

 ```  
let code = await eBay.OAuth2.getToken('v%5E1.1%23i%5E1%2p%5E3%23f%5E0%23r%5E1%23I%5E3%EUl41XzM6Qjk5QUQzOUU3OUQ5QTYwODE5NDIyRjJFOEREMzlENTBfMV8xI0VeMjYwS&expires_in=299');
```

Here is what I have done: 
1. Tried many times to use the code in the querystring of eBay.OAuth2.generateAuthUrl that never worked.
2. Tried Manually to grab the code from production Ebay URL, and paste into `GetTokens` but that also doesn't seem to work: 

Here is the production EBAY URL that I used. 
![image](https://user-images.githubusercontent.com/19142578/204009967-200f12f5-fb12-4720-8530-f1b2da07afbc.png)

I am stuck and need help. Any suggestions?

**Comment by kapooky** [comment]
I am reading the documentation, I'm only interested in the client credentials grant request, which takes in  (<client_id>:<client_secret>) as input. 

In that case why doesn't the SDK automatically mint the token for me? Given that I've already provided it with the neccesary credentials.

**Comment by dantio** [comment]
Sorry, I do not understand what are you trying to do. 
Maybe you can checkout the html source of  https://hendt.github.io/ebay-api/ 
The client token is mint automatically on request. You have to pass the correct client id and secret and set the env to sandbox.

**Comment by dantio** [comment]
Maybe you are looking for this?

// for client token
eBay.OAuth2.on('refreshClientToken', (token) => {
  console.log(token)
  // Store this token in DB
});

**Comment by kapooky** [comment]
Hi I'm just having trouble trying to get `getToken` to return the refresh object. 
![image](https://user-images.githubusercontent.com/19142578/204016799-e29618b1-bca9-4219-9be6-0073706cc28d.png)

**Comment by dantio** [comment]
The code you are passing in does not look correct to me. Where did you get it from?
This code is passed in ?code parameter in URL.

**Comment by kapooky** [comment]
From here:
![image](https://user-images.githubusercontent.com/19142578/204019417-dc324a0c-e942-46f1-8c53-5d51f1707cb0.png)

**Comment by kapooky** [comment]
> The code you are passing in does not look correct to me. Where did you get it from? This code is passed in ?code parameter in URL.

Do I have to include the expire query string parameter in the code as well? 
I keep getting:

  description: 'No XML &lt;RequestPassword&gt; or &lt;RequestToken&gt; was found in XML Request.',
  meta: {
    Timestamp: '2022-11-25T15:58:39.730Z',
    Ack: 'Failure',
    Errors: {
      ShortMessage: 'No Password and no token.',
      LongMessage: 'No XML &lt;RequestPassword&gt; or &lt;RequestToken&gt; was found in XML Request.',
      ErrorCode: 930,
      SeverityCode: 'Error',
      ErrorClassification: 'RequestError'

**Comment by dantio** [comment]
That is not the correct code. This is the url you should open to grant access. After that eBay will redirect you to your url that you specified in RuName. In this url ebay will add the code parameter 
What api do you want to call?

**Comment by kapooky** [comment]
fulfillment.getOrder
trading.UploadSiteHostedPicture

I'm trying to await eBay.OAuth2.mintApplicationAccessToken();
but it keeps complaining about no password and no token.

**Comment by kapooky** [comment]
I have a curl request that gets me the access_token allbeit with no scope(havent tested that yet). 


curl --location --request POST 'https://api.ebay.com/identity/v1/oauth2/token' \
--header 'Content-Type:  application/x-www-form-urlencoded' \
--header 'Authorization: Basic VGFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==' \
--data-urlencode 'grant_type=client_credentials'

**Comment by dantio** [comment]
That request is done automatically if you call an API. You just need to set the correct app Id client id and secret.

**Comment by kapooky** [comment]
I already had that, still doesn't work. 
I did DEBUG=ebay:* node and nowhere does it do an identity api call to mint a token.  It only injects App,Cert,App,and Dev secrets into their respective headers to construct a traditional api call.

**Comment by kapooky** [comment]
The sample code I'm using, does it work for you?
```
const eBayApi = require('ebay-api')
const eBay = new eBayApi({
    appId: "",
    devId: "",
    ruName: "",
    certId: "",
    sandbox: false,
    autoRefreshToken: true, 

    scope: [  'https://api.ebay.com/oauth/api_scope',
    'https://api.ebay.com/oauth/api_scope/sell.marketing.readonly',
    'https://api.ebay.com/oauth/api_scope/sell.marketing',
    'https://api.ebay.com/oauth/api_scope/sell.inventory.readonly',
    'https://api.ebay.com/oauth/api_scope/sell.inventory',
    'https://api.ebay.com/oauth/api_scope/sell.account',
    'https://api.ebay.com/oauth/api_scope/sell.account.readonly',
    'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly',
    'https://api.ebay.com/oauth/api_scope/sell.fulfillment',
    'https://api.ebay.com/oauth/api_scope/sell.analytics.readonly',
    'https://api.ebay.com/oauth/api_scope/sell.finances',
    'https://api.ebay.com/oauth/api_scope/sell.payment.dispute',
    'https://api.ebay.com/oauth/api_scope/commerce.identity.readonly']
    

}); 

(async () => {
  eBay.trading.GetMyeBaySelling({
    SoldList: {
        Include: true,
        OrderStatusFilter: 'AwaitingPayment',
        Pagination: {
            EntriesPerPage: 20,
            PageNumber: 1
        }
    }
}).then(result => {
    console.log(JSON.stringify(result, null, 2));
}).catch(e => {
    console.error(e);
})
})();

```

**Comment by kapooky** [comment]
Ohh I figured it out.  I noticed that without any scopes, my code would run fine. So I knew it had to be an issue with scopes.  I headed over to https://developer.ebay.com/my/keys and reviewed the scopes for my production account.  Until I realized... I was reading the Code_Grant scopes instead of the Client_Crenitials..

**Comment by dantio** [comment]
Hm I think I understand the problem:
https://github.com/hendt/ebay-api/blob/ee743174c27d342a51bde0f259090f03f478800c/src/api/traditional/index.ts#L175
This will get only the UserAccessToken.
I think a workaround would be:
```js
const token = await eBay.OAuth2.mintApplicationAccessToken();
eBay.OAuth2.setCredentials(token);
```

**Comment by kapooky** [comment]
![image](https://user-images.githubusercontent.com/19142578/204037570-fe17f1fb-c22f-4deb-806c-1a415fb1a5c4.png)

**Comment by kapooky** [comment]
> That is not the correct code. This is the url you should open to grant access. After that eBay will redirect you to your url that you specified in RuName. In this url ebay will add the code parameter What api do you want to call?

Hi okay, I've read previous issues surrounding this topic and can't figure it out. 
I will go step by step. 

1. I need authorization grant  flow because they offer more scopes than client credentials flow. (See above) 
2. To use the authorization code grant flow, I use this eBay.generateUrl()  to generate a url. 
3. 3. Upon clicking that url, I notice "code?==xxxxxxx" 
4.  I extract that code and paste it into getAuthToken()  and receive an error. 

Now, this is the wrong way of doing things I believe. What I need to create my own webserver, and when I fire up generateurl(), user will navigate and be be redirected to webserver URI with the code appended as a string parameter?
