### ISSUE TITLE
Unable to find the Account API call "getAdvertisingEligibility"

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#138]
Hello, I have been trying to locate the call `getAdvertisingEligibility` found in the Account API here:
[https://developer.ebay.com/api-docs/sell/account/resources/advertising_eligibility/methods/getAdvertisingEligibility](https://developer.ebay.com/api-docs/sell/account/resources/advertising_eligibility/methods/getAdvertisingEligibility)

Perhaps I missed it?  

Did you implement it in your library?

**Comment by dantio** [comment]
@doverradio 
Released v8.2.0 with getAdvertisingEligibility API

**Comment by doverradio** [comment]
Thanks!
