### ISSUE TITLE
FindProducts in shopping API always returns "No Match Found"

### ISSUE THREAD

**Issue by eyeruleall** [hendt/ebay-api#140]
Can you check that the FindProducts call using QueryKeywords is working properly?

No matter what I search I end up with "no matches found" as my response. 

If it is working, can you please add a working example to the project?

Additionally, if I use the FindProducts call with both CategoryID and QueryKeywords fields, I get an error saying these fields cannot be used together, despite ebay's api documentation saying these fields are supposed to be used together.

**Comment by dantio** [comment]
Maybe you are using the sandbox env?
```js
const response = await eBay.shopping.FindProducts({
  "QueryKeywords": "harry potter"
})

// returns item LEGO Die große Halle von Hogwarts - 75954 Harry Potter (75954)
```

I have also `QueryKeywords, CategoryID and ProductID cannot be used together.` when I use it together with CategoryID.
No idea why it's not working. You should ask in eBay forum.

I would suggest to use https://developer.ebay.com/devzone/finding/callref/finditemsadvanced.html or https://developer.ebay.com/api-docs/buy/browse/resources/item_summary/methods/search

**Comment by eyeruleall** [comment]
Changing the sandbox option appears to solve the issue. Thank you.
