### ISSUE TITLE
How to get rlogid from getInventoryItem call in Inventory API

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#144]
This didn't work:

```
await eBay.sell.inventory.getInventoryItem(sku, { raw: true })
```

Is there any way to do it?

**Comment by dantio** [comment]
Hey. Can you tell me more about `rLogId`? It's first time I read about this.
Maybe it's in the response headers?

```js
const response = await eBay.sell.inventory.api({
  returnResponse: true, // return the response instead of data
}).getInventoryItem(sku);

// now you have the response with headers. Maybe it's there?

```

**Comment by doverradio** [comment]
rlogid is a long alphanumeric string found in the response header of an eBay API response. Premium Support asks me for this value when I open a ticket. I suspect it is used to track down the specific request which requires support.

**Comment by dantio** [comment]
If it's in the response header you can easily access it :
```js
const response = await eBay.sell.inventory.api({
  returnResponse: true, // return the response instead of data
}).getInventoryItem(sku);

console.log(response.headers.rlogid);

```

**Comment by dantio** [comment]
@doverradio can I close this issue?

**Comment by doverradio** [comment]
Yes
