### ISSUE TITLE
listingStartDate not on type EbayOfferDetailsWithId

### ISSUE THREAD

**Issue by zenith77** [hendt/ebay-api#154]
Hi there,

As per description; listingStartDate not on type EbayOfferDetailsWithId

https://developer.ebay.com/api-docs/sell/inventory/resources/offer/methods/createOffer#request.listingStartDate

Cheers,
Col.

**Comment by zenith77** [comment]
@dantio hi there - are you able to look into this?

**Comment by dantio** [comment]
Thank you for reporting this issue. I have looked into this and already committed changes into master branch. I have found some other missing types and decided to use types directly generated by openai. I have to test it and will release a new version next week after I'm back from vacation. Right now you can use the GitHub repo as npm source. It should solve your issue.

**Comment by zenith77** [comment]
Brilliant - thanks mate! :D

And as a general point - thanks so much for your work on this library!

**Comment by zenith77** [comment]
@dantio are you able to get round to pushing out a new version?

**Comment by dantio** [comment]
@zenith77 more changes than I expected. The release `8.50` should fix all inconsistent types since they are now generated with [openapi-typescript](https://www.npmjs.com/package/openapi-typescript)

**Comment by zenith77** [comment]
Thanks Dantio - I look forward to updating!
