### ISSUE TITLE
Adding default error handler logic 

### ISSUE THREAD

**Issue by tariqazmat101** [hendt/ebay-api#156]
Hello, is there a way to add my own default error handler logic whenever the api receives an error?

**Comment by dantio** [comment]
Hey, 
there is no way right now to add custom error handler. But I can implement that.
What is your use case?

**Comment by tariqazmat101** [comment]
I'd want to send myself a notifcation via EMAIL/TEXT whenever the ebay API returns an error.

**Comment by dantio** [comment]
you can wrap the api call
```js
try {
await eBayApi.some.call()
} catch (ex) {
sendErrorMail(ex.message);
}
````

**Comment by tariqazmat101** [comment]
I'm using multiple ebay api calls and either one of them could fail, I could do as what you said and wrap each ebay call with a try catch, but it just seems redundant imo.

**Comment by dantio** [comment]
Do you use any framework? Express? NestJS? You should look up in the documentation how to catch these errors and log properly.
