### ISSUE TITLE
getItemConditionPolicies filter is not working

### ISSUE THREAD

**Issue by sughramehdi-swagkicks** [hendt/ebay-api#158]
const conditionDescriptions =
      await eBay.sell.metadata.getItemConditionPolicies('EBAY_US', {
        filter: 'categoryId:{95672}',
      });
    console.log('conditions for this category', conditionDescriptions);

Returns all category conditions. I want the filter function to work and only return filtered queries

**Comment by dantio** [comment]
Note that you must URL-encode the parameter list.
```js
{
filter: encodeURIComponent('categoryId:{95672}')
}
```

**Comment by sughramehdi-swagkicks** [comment]
This filter does not work this way as well

**Comment by dantio** [comment]
Ah the second parameter is actually the filter:
```js
await eBay.sell.metadata.getItemConditionPolicies('EBAY_US', 'categoryId:{95672}')
```

**Comment by sughramehdi-swagkicks** [comment]
it worked! Thanks
