### ISSUE TITLE
Media API

### ISSUE THREAD

**Issue by nrathi** [hendt/ebay-api#162]
Hi, any plans to support the Media API? 
https://developer.ebay.com/api-docs/commerce/media/resources/video/methods/createVideo

**Comment by dantio** [comment]
Sure, I'll work on this.

**Comment by nrathi** [comment]
Thank you so much!!

**Comment by dantio** [comment]
[v8.7.0](https://github.com/hendt/ebay-api/releases/tag/v8.7.0)

The API is implemented but I didn't test it.

**Comment by nrathi** [comment]
Thank you, I'll give it a try this week and let you know if I encounter any issues!

**Comment by nrathi** [comment]
I think you forgot to export it here: https://github.com/hendt/ebay-api/blob/ab7dedd8744b5aad5789f79444ea4e46e800994b/src/api/restful/commerce/index.ts.

**Comment by dantio** [comment]
Oh, thanks my bad. I have released just now with fixed version.
