### ISSUE TITLE
[Media API] CreateVideo

### ISSUE THREAD

**Issue by nrathi** [hendt/ebay-api#163]
https://developer.ebay.com/api-docs/commerce/media/resources/video/methods/createVideo

Very silly, but this endpoint returns the location in the header, not the body. Can you please modify it to return the location or all of the headers?

Thank you!

**Comment by dantio** [comment]
It's silli indeed. I think it's better to use the returnResponse Parameter and get the header from response. The API is beta and who knows maybe it will be changed in the future.

**Comment by nrathi** [comment]
I didn't realize that existed, thank you!

**Comment by nrathi** [comment]
Would you mind explaining how I do that?

**Comment by dantio** [comment]
Sure here is an example: https://github.com/hendt/ebay-api?tab=readme-ov-file#return-raw-restful-api-response

**Comment by nrathi** [comment]
Yes! Thank you so much.
