### ISSUE TITLE
Metric enum missing some

### ISSUE THREAD

**Issue by nodegin** [hendt/ebay-api#165]
* [ ] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [ ] Have you checked if you are using correct configuration?

**Describe the bug**
Currently the enum Metric only have the following values: {
    CLICK_THROUGH_RATE = "CLICK_THROUGH_RATE",
    LISTING_IMPRESSION_STORE = "CLICK_THROUGH_RATE",
    LISTING_IMPRESSION_TOTAL = "LISTING_IMPRESSION_TOTAL",
    LISTING_VIEWS_SOURCE_DIRECT = "LISTING_VIEWS_SOURCE_DIRECT",
    LISTING_VIEWS_SOURCE_OFF_EBAY = "LISTING_VIEWS_SOURCE_OFF_EBAY",
    LISTING_VIEWS_SOURCE_OTHER_EBAY = "LISTING_VIEWS_SOURCE_OTHER_EBAY",
    LISTING_VIEWS_SOURCE_SEARCH_RESULTS_PAGE = "LISTING_VIEWS_SOURCE_SEARCH_RESULTS_PAGE",
    LISTING_VIEWS_SOURCE_STORE = "LISTING_VIEWS_SOURCE_STORE",
    LISTING_VIEWS_TOTAL = "LISTING_VIEWS_TOTAL",
    SALES_CONVERSION_RATE = "SALES_CONVERSION_RATE",
    TRANSACTION = "TRANSACTION"
}

However according to https://developer.ebay.com/api-docs/sell/static/performance/traffic-report.html
there are more enums like `TOTAL_IMPRESSION_TOTAL` I want to use, which is not supported.
I think the metric argument should just allow user to pass the string type instead of defining limited enums.
Also the API itself support multiple by comma separated

### Code
```js
eBay.sell.analytics.getTrafficReport({
        filter: `marketplace_ids:${encodeURIComponent(
          '{EBAY_US}',
        )},date_range:${encodeURIComponent(
          `[${dateFormated}..${dateFormated}]`,
        )}`,
        dimension: 'LISTING',
        metric: 'TOTAL_IMPRESSION_TOTAL,LISTING_VIEWS_SOURCE_DIRECT',
});
```

### expected data

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No
- [x] Maybe

**Comment by dantio** [comment]
I have published it as `8.7.2-RC.0`.
