### ISSUE TITLE
Creating FixedPriceItem with ConditionDescriptors responds with error

### ISSUE THREAD

**Issue by AndrewEyesman** [hendt/ebay-api#166]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?

**Describe the bug**
I'm trying to list sports cards using the AddFixedPriceItem method but the Ebay API keeps returning errors when trying to set the item condition. The API returns different errors depending on how the item condition is specified.

When trying to set the item ConditionID I receive this error:
```
{
    ShortMessage: 'Please use the new Condition Grading conditions and descriptors.',
    LongMessage: 'The Grade, Grader and Card Condition aspects will be deprecated in the near future. Please use the new Condition Grading conditions and descriptors.',
    ErrorCode: 21920370,
    SeverityCode: 'Warning',
    ErrorClassification: 'RequestError'
}
```

I checked the [AddFixedPriceItem documentation](https://developer.ebay.com/devzone/xml/docs/reference/ebay/AddFixedPriceItem.html) and this happens because trading cards are required to use the ConditionDescriptors parameter:
"If either of these condition IDs are used, the seller is required to use the ConditionDescriptors container to provide one or more applicable Condition Descriptor name-value pairs." [Reference](https://developer.ebay.com/devzone/xml/docs/reference/ebay/AddFixedPriceItem.html#Request.Item.ConditionDescriptors)

After some research it appears the ConditionDescriptions are specified like this:
```
ConditionDescriptors: [
     {
	ConditionDescriptor: { Name: 'Card Condition', Value: '400012' },
     },
],
```

However when setting the ConditionDescriptors the API responds with this error:
```
{
  ShortMessage: 'System error.',
  LongMessage: 'System error. Unable to process your request. Please try again later.',
  ErrorCode: 10007,
  SeverityCode: 'Error',
  ErrorClassification: 'RequestError'
},
```

This obviously isn't very helpful and I'm unsure whether I'm doing something wrong or if there's an issue with this package. I've tried using only ConditionID, ConditionID with ConditionDescriptors, and only ConditionDescriptors. Nothing seems to work.

This is the full FixedPriceItem being sent to the Ebay API:
```
{
  CategoryMappingAllowed: true,
  Country: 'US',
  Currency: 'USD',
  PrimaryCategory: { CategoryID: '261328' },
  DispatchTimeMax: 3,
  ListingDuration: 'Days_7',
  PictureDetails: {
    PictureURL: [
      'https://i.sandbox.ebayimg.com/00/s/MTEzMFgxNTI1/z/CPYAAOSwQIdmB3mZ/$_1.JPG?set_id=2',
      'https://i.sandbox.ebayimg.com/00/s/MTEyNFgxNTE5/z/CPcAAOSwQIdmB3ma/$_1.JPG?set_id=2'
    ]
  },
  PostalCode: '10989',
  Quantity: '1',
  ReturnPolicy: {
    ReturnsAcceptedOption: 'ReturnsAccepted',
    RefundOption: 'MoneyBack',
    ReturnsWithinOption: 'Days_30',
    ShippingCostPaidByOption: 'Buyer'
  },
  ShippingDetails: {
    ShippingType: 'Flat',
    ShippingServiceOptions: {
      ShippingServicePriority: '1',
      ShippingService: 'USPSMedia',
      ShippingServiceCost: 2.5
    }
  },
  ConditionDescriptors: [
    {
      ConditionDescriptor: { Name: 'Card Condition', Value: '400012' }
    }
  ],
  Title: '1965 TOPPS #16 JOE MORGAN SONNY JACKSON HOUSTON ROOKIE STARS',
  Description: '1965 TOPPS #16 JOE MORGAN SONNY JACKSON HOUSTON ROOKIE STARS',
  ItemSpecifics: {
    NameValueList: [
      { Name: 'Sport', Value: 'Baseball' },
      { Name: 'Set', Value: '1965 Topps' },
      { Name: 'Year Manufactured', Value: '1965' },
      { Name: 'Team', Value: 'Houston' },
      { Name: 'Manufacturer', Value: 'Topps' },
      { Name: 'Player/Athlete', Value: 'Joe Morgan, Sonny Jackson' },
      { Name: 'Card Number', Value: '#16' }
    ]
  },
  StartPrice: 4
}
```

I could not find any examples of ConditionDescriptors being used with this package. Please let me know if I'm doing something wrong.

**Would you like to work on this issue?**

- [ ] Yes
- [ ] No
- [x] Maybe

**Comment by dantio** [comment]
Hey, I have no experience with adding trading card to ebay. But I will try to help you. As I understood, `ConditionDescriptor` is required if your `ConditionId` is either 2750 or 4000 for the category `261328`. Since you are using `400012` and this ID is mapped to Ungraded Card Condition, I would recommend setting the ConditionId to `4000` here.
Next:
https://developer.ebay.com/api-docs/user-guides/static/mip-user-guide/mip-enum-condition-descriptor-ids-for-trading-cards.html
> * Used in the Condition Descriptor Value n (where n = 1-4) or conditionDescriptor.value field with the name field of 40001.

As I understood, the correct syntax should be:
```js
 ConditionDescriptors: [
    {
      ConditionDescriptor: { Name: '40001', Value: '400012' }
    }
  ]
```

I hope this helps!

**Comment by AndrewEyesman** [comment]
Hello @dantio, unfortunately this isn't working either. However it seems the syntax you provided is correct and I was using the ConditionDescriptor.Name field incorrectly.

I logged the raw XML request and it appears everything is accurate according to the AddFixedPriceItem documentation:
```
<?xml version="1.0" encoding="utf-8"?>
<VerifyAddFixedPriceItemRequest
	xmlns="urn:ebay:apis:eBLBaseComponents">
	<RequesterCredentials>
		<eBayAuthToken>{{TOKEN}}</eBayAuthToken>
	</RequesterCredentials>
	<Item>
		<CategoryMappingAllowed>true</CategoryMappingAllowed>
		<Country>US</Country>
		<Currency>USD</Currency>
		<PrimaryCategory>
			<CategoryID>261328</CategoryID>
		</PrimaryCategory>
		<DispatchTimeMax>3</DispatchTimeMax>
		<ListingDuration>Days_7</ListingDuration>
		<PictureDetails>
			<PictureURL>https://mypicserver.com/myphoto.jpg</PictureURL>
		</PictureDetails>
		<PostalCode>10989</PostalCode>
		<Quantity>1</Quantity>
		<ReturnPolicy>
			<ReturnsAcceptedOption>ReturnsAccepted</ReturnsAcceptedOption>
			<RefundOption>MoneyBack</RefundOption>
			<ReturnsWithinOption>Days_30</ReturnsWithinOption>
			<ShippingCostPaidByOption>Buyer</ShippingCostPaidByOption>
		</ReturnPolicy>
		<ShippingDetails>
			<ShippingType>Flat</ShippingType>
			<ShippingServiceOptions>
				<ShippingServicePriority>1</ShippingServicePriority>
				<ShippingService>USPSMedia</ShippingService>
				<ShippingServiceCost>2.5</ShippingServiceCost>
			</ShippingServiceOptions>
		</ShippingDetails>
		<ConditionID>4000</ConditionID>
		<ConditionDescriptors>
			<ConditionDescriptor>
				<Name>40001</Name>
				<Value>400012</Value>
			</ConditionDescriptor>
		</ConditionDescriptors>
		<Title>1965 TOPPS #16 JOE MORGAN SONNY JACKSON HOUSTON ROOKIE STARS</Title>
		<Description>1965 TOPPS #16 JOE MORGAN SONNY JACKSON HOUSTON ROOKIE STARS</Description>
		<ItemSpecifics>
			<NameValueList>
				<Name>Sport</Name>
				<Value>Baseball</Value>
			</NameValueList>
			<NameValueList>
				<Name>Set</Name>
				<Value>1965 Topps</Value>
			</NameValueList>
			<NameValueList>
				<Name>Year Manufactured</Name>
				<Value>1965</Value>
			</NameValueList>
			<NameValueList>
				<Name>Team</Name>
				<Value>Houston</Value>
			</NameValueList>
			<NameValueList>
				<Name>Manufacturer</Name>
				<Value>Topps</Value>
			</NameValueList>
			<NameValueList>
				<Name>Player/Athlete</Name>
				<Value>Joe Morgan, Sonny Jackson</Value>
			</NameValueList>
			<NameValueList>
				<Name>Card Number</Name>
				<Value>#16</Value>
			</NameValueList>
		</ItemSpecifics>
		<StartPrice>4</StartPrice>
	</Item>
</VerifyAddFixedPriceItemRequest>
```

Unless you have any other suggestions I can only assume it's an issue with the Ebay API itself. I guess I will need to contact Ebay directly. Thank you so much for your help!

**Comment by AndrewEyesman** [comment]
Hello @dantio, I posted my issue in the Ebay developer forums and it's likely the ConditionDescriptors aren't yet supported in the sandbox environment. I think this makes sense considering I've had other issues with the sandbox. Closing this issue because it's probably not related to this package. Thanks again for your help!
