### ISSUE TITLE
EBayError typing broken since v9

### ISSUE THREAD

**Issue by nodegin** [hendt/ebay-api#173]
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?

**Describe the bug**
Was using 8.7.1 which works fine,
after upgrading to 9.0.2 the `EBayError` typing changed:
<img width="859" alt="2024-06-27 21 01 30" src="https://github.com/hendt/ebay-api/assets/8536244/406faa95-a9de-4a3d-9c05-143c043b8a71">

Changing to this fix the typing, but it seems to be wrong

<img width="628" alt="2024-06-27 21 02 00" src="https://github.com/hendt/ebay-api/assets/8536244/9532a36b-b5b8-44c3-ba69-90934369af28">

<img width="952" alt="2024-06-27 21 03 02" src="https://github.com/hendt/ebay-api/assets/8536244/0585bbef-0a16-4c0a-8f17-c7de1d9c974d">

### expected data
It should work as before

**Would you like to work on this issue?**

- [ ] Yes
- [x] No
- [ ] Maybe

**Comment by dantio** [comment]
@nodegin release `9.0.3` with type fix on status. Thank you for reporting.
