### ISSUE TITLE
Using OAuth2 in traditional API calls

### ISSUE THREAD

**Issue by liberat0r** [hendt/ebay-api#175]
Heya,

Is it possible to provide an example for using OAuth2 tokens with traditional API calls? I don't see such an example in /examples and it would be really nice to have.

Thanks in advance

**Comment by dantio** [comment]
@liberat0r If you have an OAuth token, then all traditional APIs will be called with the token.

**Comment by liberat0r** [comment]
Hey @dantio thank you very much for your answer. I suggest this be added to the documentation somewhere.
