### ISSUE TITLE
Cant find Feedback API

### ISSUE THREAD

**Issue by MickL** [hendt/ebay-api#177]
* [X] Are you running the latest version? 9.1.0
* [ X Have you included sample input, output, error, and expected output? 
* [ X Have you checked if you are using correct configuration?

**Describe the bug**
Maybe I am overseeing something but I cant find the Feedback API which is integrated according to the docs:
https://github.com/hendt/ebay-api/blob/master/src/eBayApi.ts#L132

**Comment by dantio** [comment]
@MickL 
Is this what you are looking for? https://developer.ebay.com/devzone/xml/docs/reference/ebay/GetFeedback.html

```js
eBay.trading.GetFeedback({
            FeedBackType: 'FeedbackReceivedAsSeller',
            DetailLevel: 'ReturnAll',
          }),
```

Grüße aus Berlin

**Comment by MickL** [comment]
Yes! :)

So it is hidden under trading. I kinda expected `eBay.feedback.GetFeedback()`.
