### ISSUE TITLE
Auto-refresh auth token not working

### ISSUE THREAD

**Issue by walker0643** [hendt/ebay-api#179]
* [x ] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?

**Describe the bug**
This one is pretty simple. I'm calling an eBay API (GetOrders) with a token that has expired and, rather than auto-refreshing the token, it's passing along the "Auth token is invalid" error and failing the call.

I don't know the internals of this library well enough to be sure, but I might guess that the wording is different from what the library is expecting and simply needs to check for the string "Auth token is invalid" ??

Thank you so much for all the hard work. This library is incredibly useful.

### Code
```js
  const eBay = eBayApi.fromEnv();
  eBay.OAuth2.setCredentials(token);
  eBay.OAuth2.on("refreshAuthToken", (newtoken) => {
    // this is not firing
    debug("Refresh auth token");
    TokenManager.saveToken(newtoken);
  });

  // manual refresh does work (refresh token is good)
  //await eBay.OAuth2.refreshToken();

  const raw = await eBay.trading.GetOrders({
    NumberOfDays: 2,
    OrderRole: "Seller",
    OrderStatus: "Completed",
    Pagination: {
      EntriesPerPage: 10,
      PageNumber: 1,
    },
  });
```

### Output
ebay_api /sale: Auth token is invalid. +209ms

### expected data
Return data from the GetOrders() call rather than an exception.

**Would you like to work on this issue?**

- [ ] Yes
- [x] No
- [ ] Maybe

**Comment by walker0643** [comment]
More info:

From my perspective this error (931) seems to be the same as the "hard expired" error (932). Maybe if ebay-api handled 931 like it was 932 this issue would be resolved?

**Comment by dantio** [comment]
We had never seen this error so far, thank you for reporting it. It makes sense to handle it like you said. I'll release a fix this week.

**Comment by walker0643** [comment]
Sounds good. Much appreciated!

**Comment by dantio** [comment]
@walker0643 Released `9.1.1`

**Comment by walker0643** [comment]
Confirming that the change fixed my issue. Thank you, @dantio

**Comment by elisson-zlq3x** [comment]
> Confirming that the change fixed my issue. Thank you, [@dantio](https://github.com/dantio)

Is nice to see you are still helping us when you can. After you stopped contributting at input-leap they get stucked at that same bug. Maybe everybody is too busy. At least there's already another solution. Thank you for all.
