### ISSUE TITLE
Using HTML in Description of AddFixedPriceItem results in Schema XML request error

### ISSUE THREAD

**Issue by dlaufer** [hendt/ebay-api#25]
I've got the API creating new eBay listings and everything works fine when I just include text as the description. For example, this works great:

<img width="350" alt="Screen Shot 2020-11-10 at 12 53 18 PM" src="https://user-images.githubusercontent.com/5403982/98711992-b91ee700-2353-11eb-905c-b9768b481bf7.png">

But when I add any html tags, such as the following:

<img width="392" alt="Screen Shot 2020-11-10 at 12 52 49 PM" src="https://user-images.githubusercontent.com/5403982/98711942-aad0cb00-2353-11eb-8bdd-3b1a3baa61d4.png">

...I get this error:

"Schema XML request error: SimpleDeserializer encountered a child element, which is NOT expected, in something it was trying to deserialize"

<img width="793" alt="Screen Shot 2020-11-10 at 12 53 59 PM" src="https://user-images.githubusercontent.com/5403982/98712084-d5228880-2353-11eb-90f3-2efa18ab203c.png">

**Comment by dantio** [comment]
Hey, thank you for reporting this error.

As per eBay documentation:
> you can submit your description using CDATA if you want to use HTML or XML

Can you try the following:
```js
EBay.trading.AddFixedPriceItem({
  Item: {
    Title: 'title',
    Description: {
      __cdata: '<div>test</div>'
    }
  }
})
```
Under the hood this lib is using https://www.npmjs.com/package/fast-xml-parser.

If this works I'll update the documentation.

**Comment by dlaufer** [comment]
@dantio It worked!!! Thanks so much. Love the module.

**Comment by dantio** [comment]
Updated docs: https://hendt.gitbook.io/ebay-api/#trading-addfixedpriceitem-cdata

**Comment by doverradio** [comment]
Hey I'm having a similar problem but with the itemSpecifics.  

```Error [EbayApiError]: XML Error Text: &quot;; nested exception is:
        org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 2610; The entity name must immediately follow the &apos;&amp;&apos; in the entity reference.&quot;.```

I thought the issue was that for apostrophe, quotations, and ampersands to be replaced.  Example: `5'3" x 7'2"`  would become `5&apos; 3&quot;  x 7&apos; 2&quot;`.  However, despite replacing these I am constantly getting the listings rejected due to this error.  Is there any advice?

**Comment by dantio** [comment]
@doverradio Please you provide the whole text.

**Comment by doverradio** [comment]
Weird but I ultimately ended up using `AddItem` call instead and it accepted `5'3" x 7'2"` without issues.  Ended up switching everything over to AddItem from now.  Thanks!

**Comment by JorensM** [comment]
Hello, I'm getting the same error with `ItemSpecifics`, here is what my property looks like:

```
ItemSpecifics: {
      __cdata: `
          <NameValueList>
             <Name>
                   Brand
              </Name>
              <Value>
                  Cool Brand
               </Value>
           </NameValueList>
           <NameValueList>
                <Name>
                     Type
                </Name>
                 <Value>
                     Cool Type
                  </Value>
             </NameValueList>`
},
```

Any help appreciated, thanks!
