### ISSUE TITLE
Having Trouble Listing Images

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#32]
Hi, I successfully listed some items using your library but can't seem to get the pictures to list.  

My images are being sent this way:

```
    PictureDetails: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
```
Each of the "Object" items looks like this: 
`'https://imageurl.....'`

So that the array appears like this:
 ```
 pictureURLs: [
    'https://imageurl.....jpeg',
    'https://imageurl.....jpeg',
    'https://imageurl.....jpeg',
    'https://imageurl.....jpeg'
  ]
```
What is the correct way to send pictures to ebay when I list items though your library?

**Comment by dantio** [comment]
Hm I think it's should be `PictureURLs` with uppercase P. It should look like this.
```json
"PictureDetails": {
  "PictureURL":  [
   "https://imageurl.....jpeg",
   "https://imageurl.....jpeg",
   "https://imageurl.....jpeg",
   "https://imageurl.....jpeg'
 ]
}
```

Also keep in mind, the images must be hosted by EPS. So you need to upload them to eBay EPS first.

**Comment by dantio** [comment]
@doverradio can I close this issue?
