### ISSUE TITLE
Restrict/Update Typescript Types

### ISSUE THREAD

**Issue by Borduhh** [hendt/ebay-api#35]
Saw that in several instances, `any` is used when I believe the type should be known.

For example:
**/src/api/resetful/index.ts**
```
    private async doRequest(
        method: keyof ILimitedRequest,
        url: string,
        config: any,
        data?: any
    ): Promise<any> {
        ...
    }
```

Could be restricted to:
```
    private async doRequest(
        method: keyof ILimitedRequest,
        url: string,
        config: AxiosRequestConfig,
        data?: {[key: string]: any}
    ): Promise<any> {
        ...
    }
```

Which would limit the parameters being passed in and make the program that much safer.

If this makes sense and you agree, I could take a whack at it this weekend.

**Comment by dantio** [comment]
Hey! Thank you for suggestion. 
Yes you are right and I'm already on it. I'll will refactor the whole "doRequest" part anyway and will add better type checks!

**Comment by dantio** [comment]
Types will be refactored soon. I'll close this ticket for now.
