### ISSUE TITLE
Add enums

### ISSUE THREAD

**Issue by olliechick** [hendt/ebay-api#36]
Many types are enums, defined by eBay. These enums should be added so that types can be restricted to these enums, instead of strings.

For example, the type [CategoryType](https://developer.ebay.com/api-docs/sell/account/types/api:CategoryType), which is currently:
```ts
export type CategoryType = {
    default?: boolean
    name: string
}
```

Would become:
```ts
export type CategoryType = {
    default?: boolean
    name: CategoryTypeEnum
}
```

The enum [CategoryTypeEnum](https://developer.ebay.com/api-docs/sell/account/types/api:CategoryTypeEnum) could be defined as:
```ts
export enum CategoryTypeEnum {
    MOTORS_VEHICLES = 'MOTORS_VEHICLES',
    ALL_EXCLUDING_MOTORS_VEHICLES = 'ALL_EXCLUDING_MOTORS_VEHICLES'
```

Or, to use TypeScript case conventions:
```ts
export enum CategoryTypeEnum {
    MotorsVehicles = 'MOTORS_VEHICLES',
    AllExcludingMotorsVehicles = 'ALL_EXCLUDING_MOTORS_VEHICLES'
}
```

This will improve type safety in the library.

**Comment by dantio** [comment]
Yes! I want to have all Enums and Types in this lib!

I already started to refactor a little in my "next" branch: https://github.com/hendt/ebay-api/tree/next

The missing CategoryTypeEnum is also added.

**Comment by dantio** [comment]
`CategoryType` Enum was added.

https://github.com/hendt/ebay-api/blob/master/src/enums/restfulEnums.ts#L142
