### ISSUE TITLE
Can ebay-api be used to create business policies - returns, shipping, and payments?

### ISSUE THREAD

**Issue by doverradio** [hendt/ebay-api#57]
I need to create all the business policies for a bunch of members of my website.  

Meaning, the returns, shipping, and payments policies.

Can this be done through ebay-api?

**Comment by dantio** [comment]
Hey, what kind of eBay APIs do you need to call exactly?

**Comment by doverradio** [comment]
I suppose it's the [eBay Business Policies Management API](https://developer.ebay.com/Devzone/business-policies/Concepts/BusinessPoliciesAPIGuide.html).

**Comment by dantio** [comment]
> Important! This API is deprecated and will be decommissioned on January 31, 2022. We recommend that you migrate to the fulfillment_policy, payment_policy, and return_policy resources of the Account API to set up and manage all of your fulfillment, payment, and return business policies.

You want to use https://developer.ebay.com/api-docs/sell/account/resources/methods

And yes, it's implemented: https://github.com/hendt/ebay-api/blob/master/src/api/restful/sell/account/index.ts

```
// e.g.
await eBay.sell.account.getPrivileges()
```
