### ISSUE TITLE
Set grant type

### ISSUE THREAD

**Issue by workteam123** [hendt/ebay-api#65]
Can you set grant type. I would like to set it to client_credentials

**Comment by dantio** [comment]
It's client_credentials per default if you don't set anything.

**Comment by workteam123** [comment]
Thanks Danill

Have you come across this error?
error: 'invalid_grant',
error_description: 'the provided authorization grant code is invalid or was
issued to another client'
using eBay.OAuth2.getToken(code)

Gary

**Comment by dantio** [comment]
I once had this error because I called the "getToken()" method twice. Or try to output the `code` maybe it's malformed.

**Comment by dantio** [comment]
@workteam123 can I close this issue?
