### ISSUE TITLE
Token giving access to ebay store question

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [hendt/ebay-api#66]
Hey...I'm sorry to come back with another question.

With my GetNotificationPreferences, and SetNotificationPreferences and getOrders working in sandbox. I've added some production keys.
I've then got the owner of the ebay store account to log in and authorize a token and stored the token locally. And I can use that token to get notification preferences and orders, getting success API responses.

However, it's not bringing back ANY orders, and I'm not getting any notifications even though they have been set by the API. I can even use the API Explorer in eBay to check with the token: -

![image](https://user-images.githubusercontent.com/58920692/116696602-094d3c80-a9ba-11eb-8ee9-b938a6d2d675.png)

![image](https://user-images.githubusercontent.com/58920692/116696710-2a159200-a9ba-11eb-9935-89da844b5b03.png)

What am I missing? Why can't I get orders from the ebay store.
I'm using the sandbox = false; and the production cert, app ids etc...

**Comment by dantio** [comment]
The response is from eBay without any errors... 
> The Fulfillment API covers only the transactions that have completed the checkout process. This API does not cover pending payment purchases that require upfront payment before shipment.

Maybe you are looking for a different API?
What do you see in https://developer.ebay.com/my/api_test_tool?index=0&api=fulfillment&call=order__GET&variation=json&env=production ?

You can also try:
```
eBay.trading.GetMyeBaySelling({
      SoldList: {
        Include: true
      }
    })
```

**Comment by sunrunner4kr-simon** [comment]
The store has 100s of orders, some pending, some already checked out

![image](https://user-images.githubusercontent.com/58920692/116740064-6235c880-a9ec-11eb-84af-1ec90f8e0c99.png)

**Comment by sunrunner4kr-simon** [comment]
eBay.trading.GetMyeBaySelling({
      SoldList: {
        Include: true
      }
    })

also returns nothing

it must be to do with linking my ebay developer account with my production keys to the ebay store. I thought getting the ebay store account user to authorize the token would be enough. But maybe there's something else that needs doing?

**Comment by dantio** [comment]
Hm double check if you really use production keys and use sandbox: false everywhere. It must work since we also use the getorders call heavily

**Comment by sunrunner4kr-simon** [comment]
I had the seller log in and authorize in front of me and it's working!

I think it must have been a problem with the log in, maybe when logging in they were also logged in already to another eBay account, so it didn't authorize with the correct account...who knows

Thanks again!!
