### ISSUE TITLE
How to authroize the client?

### ISSUE THREAD

**Issue by BoxOfCereal** [hendt/ebay-api#80]
There are examples on how to refresh the client and oauth tokens and and example to get an oauth token. I'm trying to simply use the API from a client and am struggling to understand how to authenticate calls without having to constantly open a new tab and copy in the code.

**Comment by dantio** [comment]
You have to do it once and save the token to DB or some persisten storage. Afterwards grab the token and also setup the refresh token event.

If you only use Traditional API you could also use the Auth'N'Auth token. This is valid for 2 years I think.

For restful, most of the "get or list" APIs only require client credentials. This is done automatically so you don't even need to do the authentication flow.

Which APIs do you use? Are you using webserver like express?

**Comment by dantio** [comment]
@BoxOfCereal can we close this issue?
