### ISSUE TITLE
Create and delete inventory location endpoints are not implemented

### ISSUE THREAD

**Issue by olliechick** [hendt/ebay-api#9]
In the Inventory API, there are 7 endpoints related to location. These 5 have been implemented:
- disableInventoryLocation
- enableInventoryLocation
- getInventoryLocation
- getInventoryLocations
- updateInventoryLocation

But these 2 have not:
- createInventoryLocation
- deleteInventoryLocation

See https://developer.ebay.com/api-docs/sell/inventory/resources/methods for the eBay docs on the Inventory API.

**Comment by dantio** [comment]
Thank you. I'll add the missed calls.

**Comment by dantio** [comment]
@olliechick 
Did it work? Can we close this issues?

**Comment by olliechick** [comment]
Yup :)
