### ISSUE TITLE
The warning reply from UploadSiteHostedPictures is treated as an outright error.

### ISSUE THREAD

**Issue by dylancristy** [hendt/ebay-api#93]
According to the [image guidelines on eBay](https://developer.ebay.com/devzone/merchant-products/catalog-best-practices/content/images.html):

> If your image is less than 1,000 pixels (width + height in pixels), a warning is provided but the picture is not rejected.

However, in your `handleEBayJsonResponse` function, you're not checking the `Ack` property of the response, only checking that the `Errors` property is not `null`.  Since the warning message from eBay comes in the `Errors` property, your code detects that and then throws your own `EbayApiError`, so the original response never gets through and I do not get a chance to see the still valid `SiteHostedPictureDetails` response:

![Screen Shot 2021-10-11 at 3 18 48 PM](https://user-images.githubusercontent.com/13592628/136845773-c8352b8c-741c-4478-8096-8625c293fe23.png)

Is there any way to get those warnings handled as warnings and allowing those responses through, instead of handling them as outright errors and throwing `EbayApiError`s?

**Comment by dantio** [comment]
Good catch. Thank you for reporting it! I'll add a check for the Ack Warning.

**Comment by dantio** [comment]
I have added the check. Please verify if it works for you.
